### ISSUE TITLE
Overlay issues / workarounds with certain ROMs appearing behind their bezel slightly

### ISSUE THREAD

**Issue by movisman** [cosmo0/retropie-overlays-arcade-artwork#4]
Hey there,

Hope you are good. This pack is really great, it's helped me easily get together the overlays for my small collection of arcade games on my RetroPie system running on my Ubuntu 18.10 Server machine (which is plugged into the TV).

I actually installed them manually rather than via arcade manager, as was familiar with where all this stuff needs to go.

After I installed all 107 overlays for my system, I went through and tested each one. For reference, I am using lr-mame (current) because i'm on x86 with no performance restrictions, along with a 0.203 romset. Also for reference, my retroarch settings are pretty much default, with the exception of a crt-shader and basic unrelated stuff to this. Integer scale and all that stuff is off.

Most of them worked first time, however I thought i'd raise an issue for you for some where the default screen size displays slightly too large for the overlay, and thus partially appears behind it.

Opening the PNG files you can see some of the offenders have the bezel part a bit wider than others (eg. 296px, and 255px - i think, most of the others are 240px either side). Anyway, the files which I noticed were:

armwar
bionicc
dariusg
dbreed
elvactr
ga2
gradius4
pbobble4
pitfight
rbisland
splatter
ssriders
tmnt
vendetta
wof

There will obviously be others, but these ones didn't display quite right. Also the original tapper was messed up too, fyi. However I ended up changing this for rbtapper which has a more conventional overlay that works ok.

To solve this issue, I had two options. Either I resize the bezels so the edges were narrower, but at the expense of distorting the image slightly. In the end I did some calculations and worked out custom viewports for the above and placed them into their respective .zip.cfg files (vendetta.zip.cfg) for example. This means the display slightly smaller, but doesn't go behind the overlay and is also still the correct aspect (I scaled the values appropriately).

If you are interested, for the above this is what worked (there were only two variants of sizing required):

elvactr
rbisland
vendetta

add this to their .zip.cfg files:

aspect_ratio_index = "23"
custom_viewport_width = "1408"
custom_viewport_height = "1056"
custom_viewport_x = "256"
custom_viewport_y = "12"

and for these:

armwar
bionicc
dariusg
dbreed
ga2
gradius4
pbobble4
pitfight
splatter
ssriders
tmnt
wof

add this:

aspect_ratio_index = "23"
custom_viewport_width = "1328"
custom_viewport_height = "996"
custom_viewport_x = "296"
custom_viewport_y = "42"

This then sorts the roms so they display within the bezel, without needing to edit/distort the bezel itself. Either way would work though. FYI, aspect_ratio_index = "23" is the latest custom value, since RetroArch v1.7.4.

There are obviously others that will have this overlay issue, but just pointing out the ones I had to work on. It would be a lot of work to go through all of them of course.

Also, on a side note, vendetta.png had a nasty white haze over the whole image, which I see you make reference to in the readme. I solved this by opening the PNG, deleting the transparent area (even though it appeared ok in GIMP) and re-exporting.

Hope this helps.

Cheers!

**Comment by cosmo0** [comment]
Thank you so much!

As you can guess I haven't tested most of these overlays. First because it would require much more time than I want to spend, and second because many of these don't even work on my Pi.

I will check the games you noted soon.

**Comment by movisman** [comment]
No worries, thanks for the reply! It was a bit of a long winded message from myself.

I gathered with the sheer amount of overlays which you pulled together from various sources, there was no way they would all be tested and of course, as you are on a Pi there are quite a lot of games which won't run nicely either.

It is only a minor issue but thought i'd share my workaround with you in case you fancied incorporating it at any point.

Overlays are a minefield in terms of which ones work well eh!

Cheers again.

**Comment by cosmo0** [comment]
Fixed (thanks @movisman even though you certainly forgot about that haha)

**Comment by movisman** [comment]
I did!! Haha!
